const icons: icons = {
    danger: '⚠️',
    info: 'ℹ️',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    question: '❓',
    arrowRight: '➡️',
    arrowLeft: '⬅️',
    arrowUp: '⬆️',
    arrowDown: '⬇️',
    check: '✔️',
    cross: '✖️',
    star: '⭐',
    heart: '❤️',
    lock: '🔒',
    unlock: '🔓',
    bell: '🔔',
    calendar: '📅',
    clock: '⏰',
    file: '📄',
    folder: '📁',
    trash: '🗑️',
    edit: '✏️',
    mail: '✉️',
    phone: '📞',
    map: '🗺️',
    pin: '📍',
    chat: '💬',
    search: '🔍',
    settings: '⚙️',
    sun: '☀️',
    moon: '🌙',
};

export default icons